### ISSUE TITLE
[ERROR] [Entrypoint]: mariadbd failed while attempting to check config

### ISSUE THREAD

**Issue by ps915** [SoftCreatRMedia/wsc-dockerized#10]
Hi SoftCreatR,

first of all, thanks a lot for your work, but i ran into some errors. 

MariaDB won't start. Any idea, how to resolve this?

![image](https://github.com/SoftCreatRMedia/wsc-dockerized/assets/3420935/b2113085-7d3f-4c75-a136-ebd22dc344fa)

**Comment by SoftCreatR** [comment]
Maybe a problem with docker desktop on Windows. I'll check that.

**Comment by ps915** [comment]
works now! =) Thanks!
