### ISSUE TITLE
Installation process failed

### ISSUE THREAD

**Issue by BenJule** [SoftCreatRMedia/wsc-dockerized#2]
System Information

PHP Version:

8.1.21

WoltLab Suite Core:

n/a

Peak Memory Usage:

1.251 MiB

Request URI:

POST /install.php

Referrer:

https://wsc-fr-01.s3debsrv.ovh/install.php

User Agent:

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

Error

Error Type:

Exception

Error Message:

Refusing to skip a step.

File:

/wsc/WCFSetup-77ab12f9070b7fce/install/files/lib/system/WCFSetup.class.php (198)

Stack Trace:

#0 /wsc/WCFSetup-77ab12f9070b7fce/install/files/lib/system/WCFSetup.class.php (279):
wcf\system\WCFSetup->calcProgress(18)
#1 /wsc/WCFSetup-77ab12f9070b7fce/install/files/lib/system/WCFSetup.class.php (94):
wcf\system\WCFSetup->dispatch()
#2 /wsc/install.php (1306):
wcf\system\WCFSetup->__construct()

**Comment by foxly-it** [comment]
How did you fix this error?

**Comment by SoftCreatR** [comment]
Fixed via https://github.com/WoltLab/WCF/commit/9719466bed29eb0379409db8d1838d19295bf3ea
