### ISSUE TITLE
Step 2/6 depends

### ISSUE THREAD

**Issue by foxly-it** [SoftCreatRMedia/wsc-dockerized#3]
I have the problem that the unrolling of the container constantly freezes at step 2/6. Even after 30 minutes. How long does this step usually take? I tried it on a CX11 (Hetzner Cloud) with freshly installed Debian 12. I also tried this on a CAX11 (Hetzner Cloud) with Ubuntu 22.04.

**Comment by SoftCreatR** [comment]
Can you describe your steps?

**Comment by foxly-it** [comment]
On a freshly installed Debian 12 or Ubuntu 22.04:

### Step 1: Install Docker and Docker Compose according to [https://docs.docker.com/engine/install/](https://docs.docker.com/engine/install/)
### Step 2: 

```
cd /home
git clone https://github.com/SoftCreatR/wsc-dockerized
cd wsc-dockerized
cp .env.example .env && nano .env
```

```
# WoltLab Suite
WSC_VERSION=6.0

# PHP
PHP_VERSION=8.1

# MySQL
MYSQL_DATABASE=wscdb
MYSQL_USER=wscuser
MYSQL_PASSWORD=p@ssw0rd
```

Save and close

And now docker-compose up. From step 2/6, the time counts, but he never finishes.

**Comment by SoftCreatR** [comment]
Try `master` instead of `6.0`.

**Comment by foxly-it** [comment]
> Try `master` instead of `6.0`.

<img width="859" alt="image" src="https://github.com/SoftCreatRMedia/wsc-dockerized/assets/81775975/fb9ed583-17e0-4ea7-a962-ee148564d38b">

:-/ i can't imagine it should take that long

**Comment by SoftCreatR** [comment]
Seems like a network issue. Try to configure the MTU in `/etc/docker/daemon.json` like

```json
{
  "mtu": 1450,
  "default-network-opts": {"bridge": {"com.docker.network.driver.mtu": "1450"}}
}
```

**Comment by foxly-it** [comment]
> Seems like a network issue. Try to configure the MTU in `/etc/docker/daemon.json` like
> 
> ```json
> {
>   "mtu": 1450,
>   "default-network-opts": {"bridge": {"com.docker.network.driver.mtu": "1450"}}
> }
> ```

Ok, that was the problem. I did not think about the MTU of Docker. Thank you Sascha.
