### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by foxly-it** [SoftCreatRMedia/wsc-dockerized#4]
Even though this "error" has been reported before, this was closed by the author without a response.
After listing the system requirements, the installation fails. The Docker logs are also not very informative.

```
Error

Error Type:
Exception
Error Message:
Refusing to skip a step.
File:
/wsc/WCFSetup-f9427022a932aa61/install/files/lib/system/WCFSetup.class.php (198)
Stack Trace:
#0 /wsc/WCFSetup-f9427022a932aa61/install/files/lib/system/WCFSetup.class.php (279):
wcf\system\WCFSetup->calcProgress(18)
#1 /wsc/WCFSetup-f9427022a932aa61/install/files/lib/system/WCFSetup.class.php (94):
wcf\system\WCFSetup->dispatch()
#2 /wsc/install.php (1306):
wcf\system\WCFSetup->__construct()
```
<img width="1470" alt="image" src="https://github.com/SoftCreatRMedia/wsc-dockerized/assets/81775975/71d31e6c-cf56-4e69-acd0-3f707338db37">

**Comment by SoftCreatR** [comment]
https://www.woltlab.com/community/thread/301247-refusing-to-skip-a-step/

**Comment by SoftCreatR** [comment]
Fixed via https://github.com/WoltLab/WCF/commit/9719466bed29eb0379409db8d1838d19295bf3ea
